// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PinPoint.Data;

#nullable disable

namespace PinPoint.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251025125043_AdditionalNotesNull")]
    partial class AdditionalNotesNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b8a44de3-054d-44f4-8d22-b6c7286ce135",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = "4bf6db49-c852-409f-900f-48a83f70047b",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "7ff01497-5a99-4470-87ee-d8e8a267a99b",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3f720a9f-e689-41fb-b3a9-52a07410bf5f",
                            Name = "Developer",
                            NormalizedName = "DEVELOPER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ab3dca9e-4c1d-41e9-9c9b-b4e047cd12f4",
                            RoleId = "3f720a9f-e689-41fb-b3a9-52a07410bf5f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PinPoint.Data.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitiesBeforePain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("PainDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PainIntensity")
                        .HasColumnType("integer");

                    b.Property<int>("ReliefEffectiveness")
                        .HasColumnType("integer");

                    b.Property<string>("ReliefMethodsTried")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SymptomId")
                        .HasColumnType("integer");

                    b.Property<int?>("TriggerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SymptomId");

                    b.HasIndex("TriggerId");

                    b.ToTable("PainEntries");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntryLocation", b =>
                {
                    b.Property<int>("PainEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("PainEntryId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("PainEntryLocation");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntrySymptom", b =>
                {
                    b.Property<int>("PainEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.HasKey("PainEntryId", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.ToTable("PainEntrySymptom");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntryTrigger", b =>
                {
                    b.Property<int>("PainEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerId")
                        .HasColumnType("integer");

                    b.HasKey("PainEntryId", "TriggerId");

                    b.HasIndex("TriggerId");

                    b.ToTable("PainEntryTrigger");
                });

            modelBuilder.Entity("PinPoint.Data.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("PinPoint.Data.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("PinPoint.Migrations.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ab3dca9e-4c1d-41e9-9c9b-b4e047cd12f4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9c1ac7ab-11d5-49b5-a4eb-c11706478bc4",
                            DateOfBirth = new DateOnly(1990, 9, 5),
                            Email = "dev@pinpoint.com.au",
                            EmailConfirmed = true,
                            FirstName = "Default",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "DEV@PINPOINT.COM.AU",
                            NormalizedUserName = "DEV@PINPOINT.COM.AU",
                            PasswordHash = "AQAAAAIAAYagAAAAEEQhMdTf17FXe9OfnXMeM+SgYr78OFnzH0VerNh6FhCtS33AAzM5xHiMa0yU79HeLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6fb5db0-dca3-4726-bf05-8d2a1eb0b980",
                            TwoFactorEnabled = false,
                            UserName = "dev@pinpoint.com.au"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PinPoint.Migrations.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PinPoint.Migrations.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinPoint.Migrations.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PinPoint.Migrations.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PinPoint.Data.PainEntry", b =>
                {
                    b.HasOne("PinPoint.Data.Location", null)
                        .WithMany("PainEntries")
                        .HasForeignKey("LocationId");

                    b.HasOne("PinPoint.Data.Symptom", null)
                        .WithMany("PainEntries")
                        .HasForeignKey("SymptomId");

                    b.HasOne("PinPoint.Data.Trigger", null)
                        .WithMany("PainEntries")
                        .HasForeignKey("TriggerId");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntryLocation", b =>
                {
                    b.HasOne("PinPoint.Data.Location", "Location")
                        .WithMany("PainEntryLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinPoint.Data.PainEntry", "PainEntry")
                        .WithMany("PainEntryLocations")
                        .HasForeignKey("PainEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("PainEntry");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntrySymptom", b =>
                {
                    b.HasOne("PinPoint.Data.PainEntry", "PainEntry")
                        .WithMany("PainEntrySymptoms")
                        .HasForeignKey("PainEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinPoint.Data.Symptom", "Symptom")
                        .WithMany("PainEntrySymptoms")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PainEntry");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntryTrigger", b =>
                {
                    b.HasOne("PinPoint.Data.PainEntry", "PainEntry")
                        .WithMany("PainEntryTriggers")
                        .HasForeignKey("PainEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinPoint.Data.Trigger", "Trigger")
                        .WithMany("PainEntryTriggers")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PainEntry");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("PinPoint.Data.Location", b =>
                {
                    b.Navigation("PainEntries");

                    b.Navigation("PainEntryLocations");
                });

            modelBuilder.Entity("PinPoint.Data.PainEntry", b =>
                {
                    b.Navigation("PainEntryLocations");

                    b.Navigation("PainEntrySymptoms");

                    b.Navigation("PainEntryTriggers");
                });

            modelBuilder.Entity("PinPoint.Data.Symptom", b =>
                {
                    b.Navigation("PainEntries");

                    b.Navigation("PainEntrySymptoms");
                });

            modelBuilder.Entity("PinPoint.Data.Trigger", b =>
                {
                    b.Navigation("PainEntries");

                    b.Navigation("PainEntryTriggers");
                });
#pragma warning restore 612, 618
        }
    }
}
